<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Slums.TestSupport</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Slums.Infrastructure\Slums.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="TestAssemblyContentSetup.cs" />
  </ItemGroup>

</Project>
