using System.Text.Json.Serialization;
using Slums.Core.Investments;

namespace Slums.Infrastructure.Persistence;

[JsonSourceGenerationOptions(UseStringEnumConverter = true, WriteIndented = true)]
[JsonSerializable(typeof(GameSessionSaveDocument))]
[JsonSerializable(typeof(GameSessionSnapshot))]
[JsonSerializable(typeof(GameSessionClockSnapshot))]
[JsonSerializable(typeof(GameSessionPlayerSnapshot))]
[JsonSerializable(typeof(GameSessionWorldSnapshot))]
[JsonSerializable(typeof(ActiveDistrictConditionSnapshot))]
[JsonSerializable(typeof(List<ActiveDistrictConditionSnapshot>))]
[JsonSerializable(typeof(GameSessionRelationshipSnapshot))]
[JsonSerializable(typeof(GameSessionNpcRelationshipSnapshot))]
[JsonSerializable(typeof(GameSessionJobProgressSnapshot))]
[JsonSerializable(typeof(GameSessionJobTrackSnapshot))]
[JsonSerializable(typeof(GameSessionCrimeSnapshot))]
[JsonSerializable(typeof(GameSessionWorkSnapshot))]
[JsonSerializable(typeof(GameSessionRunSnapshot))]
[JsonSerializable(typeof(GameSessionNarrativeSnapshot))]
[JsonSerializable(typeof(NarrativeProgressSnapshot))]
[JsonSerializable(typeof(InvestmentSnapshot))]
[JsonSerializable(typeof(List<InvestmentSnapshot>))]
[JsonSerializable(typeof(GameSessionHouseholdAssetsSnapshot))]
[JsonSerializable(typeof(OwnedPetSnapshot))]
[JsonSerializable(typeof(List<OwnedPetSnapshot>))]
[JsonSerializable(typeof(OwnedPlantSnapshot))]
[JsonSerializable(typeof(List<OwnedPlantSnapshot>))]
[JsonSerializable(typeof(GameSessionRamadanSnapshot))]
[JsonSerializable(typeof(GameSessionCommunityEventSnapshot))]
[JsonSerializable(typeof(GameSessionDistrictHeatSnapshot))]
[JsonSerializable(typeof(DistrictHeatEntrySnapshot))]
[JsonSerializable(typeof(List<DistrictHeatEntrySnapshot>))]
[JsonSerializable(typeof(GameSessionTerritorySnapshot))]
[JsonSerializable(typeof(TerritoryDistrictSnapshot))]
[JsonSerializable(typeof(GameSessionEconomySnapshot))]
[JsonSerializable(typeof(NpcEconomyEntrySnapshot))]
[JsonSerializable(typeof(PlayerDebtEntrySnapshot))]
[JsonSerializable(typeof(DebtorAmountSnapshot))]
[JsonSerializable(typeof(List<NpcEconomyEntrySnapshot>))]
[JsonSerializable(typeof(List<PlayerDebtEntrySnapshot>))]
[JsonSerializable(typeof(List<DebtorAmountSnapshot>))]
[JsonSerializable(typeof(GameSessionPhoneSnapshot))]
[JsonSerializable(typeof(PhoneMessageSnapshot))]
[JsonSerializable(typeof(List<PhoneMessageSnapshot>))]
[JsonSerializable(typeof(GameSessionTipSnapshot))]
[JsonSerializable(typeof(TipEntrySnapshot))]
[JsonSerializable(typeof(List<TipEntrySnapshot>))]
internal sealed partial class SaveGameJsonContext : JsonSerializerContext
{
}
