namespace Slums.Core.Narrative;

public static class NarrativeKnots
{
    public const string CrisisIntroduction = "crisis_introduction";
    public const string CrisisClassification = "crisis_classification";
    public const string CrisisAppeal = "crisis_appeal";
    public const string CrisisHeatEmergency = "crisis_heat_emergency";
    public const string CrisisCommitment = "crisis_commitment";
    public const string CrisisResolution = "crisis_resolution";
    public const string CrisisEvidenceCallback = "crisis_evidence_callback";
    public const string CrisisMutualAidCallback = "crisis_mutual_aid_callback";
    public const string CrisisDiversionCallback = "crisis_diversion_callback";
    public const string CrisisPublicPressureCallback = "crisis_public_pressure_callback";
    public const string CrimeFirstSuccess = "crime_first_success";
    public const string CrimeWarning = "crime_warning";
    public const string MotherClinicFirstVisit = "mother_clinic_first_visit";
    public const string EventPublicWorkHeat = "event_public_work_heat";
    public const string BackgroundMedicalClinic = "background_medical_clinic";
    public const string EventMotherWrongMoney = "event_mother_wrong_money";
    public const string EventNeighborWatch = "event_neighbor_watch";
    public const string EventRentFinalWarning = "event_rent_final_warning";
    public const string EventInvestmentSuspension = "event_investment_suspension";
    public const string BackgroundPrisonerHeat = "background_prisoner_heat";
    public const string BackgroundSudaneseSolidarity = "background_sudanese_solidarity";

    public const string CrimeHananFenceSuccess = "crime_hanan_fence_success";
    public const string CrimeHananFenceDetected = "crime_hanan_fence_detected";
    public const string CrimeHananFenceFailure = "crime_hanan_fence_failure";
    public const string CrimeYoussefDropSuccess = "crime_youssef_drop_success";
    public const string CrimeYoussefDropDetected = "crime_youssef_drop_detected";
    public const string CrimeYoussefDropFailure = "crime_youssef_drop_failure";
    public const string CrimeUmmKarimErrandSuccess = "crime_ummkarim_errand_success";
    public const string CrimeUmmKarimErrandDetected = "crime_ummkarim_errand_detected";
    public const string CrimeUmmKarimErrandFailure = "crime_ummkarim_errand_failure";
    public const string CrimeSafaaSkimSuccess = "crime_safaa_skim_success";
    public const string CrimeSafaaSkimDetected = "crime_safaa_skim_detected";
    public const string CrimeSafaaSkimFailure = "crime_safaa_skim_failure";
    public const string CrimeImanBundleSuccess = "crime_iman_bundle_success";
    public const string CrimeImanBundleDetected = "crime_iman_bundle_detected";
    public const string CrimeImanBundleFailure = "crime_iman_bundle_failure";

    public const string CrimeWorkshopContrabandSuccess = "crime_workshop_contraband_success";
    public const string CrimeWorkshopContrabandDetected = "crime_workshop_contraband_detected";
    public const string CrimeWorkshopContrabandFailure = "crime_workshop_contraband_failure";
    public const string CrimeBulaqProtectionSuccess = "crime_bulaq_protection_success";
    public const string CrimeBulaqProtectionDetected = "crime_bulaq_protection_detected";
    public const string CrimeBulaqProtectionFailure = "crime_bulaq_protection_failure";

    public const string CrimeHananCover = "crime_hanan_cover";
    public const string CrimeHananSalvage = "crime_hanan_salvage";
    public const string CrimeYoussefTipoff = "crime_youssef_tipoff";
    public const string CrimeYoussefEscape = "crime_youssef_escape";
    public const string CrimeSafaaReroute = "crime_safaa_reroute";
    public const string CrimeSafaaSalvage = "crime_safaa_salvage";
    public const string CrimeImanCover = "crime_iman_cover";
    public const string CrimeImanExit = "crime_iman_exit";

    public const string EventArrestCloseCall = "event_arrest_close_call";
    public const string EventHonestMilestone = "event_honest_milestone";
    public const string EventCommunityAftermath = "event_community_aftermath";
    public const string EventEmbarrassmentRecovery = "event_embarrassment_recovery";
    public const string BackgroundPrisonerKhalid = "background_prisoner_khalid";
    public const string BackgroundSudaneseMariam = "background_sudanese_mariam";
    public const string EventYoussefEmbedded = "event_youssef_embedded";
    public const string EventNadiaSuspicion = "event_nadia_suspicion";
    public const string CentralMotherArc = "central_mother_arc";
    public const string CentralMonaArc = "central_mona_arc";
    public const string CentralSalmaArc = "central_salma_arc";
    public const string CentralMahmoudArc = "central_mahmoud_arc";
    public const string CentralUmmKarimArc = "central_ummkarim_arc";
    public const string CentralMotherVulnerability = "central_mother_vulnerability";
    public const string CentralMotherConflict = "central_mother_conflict";
    public const string CentralMotherReckoning = "central_mother_reckoning";
    public const string CentralMotherOutcome = "central_mother_outcome";
    public const string CentralMonaTransaction = "central_mona_transaction";
    public const string CentralMonaVulnerability = "central_mona_vulnerability";
    public const string CentralMonaConflict = "central_mona_conflict";
    public const string CentralMonaOutcome = "central_mona_outcome";
    public const string CentralSalmaTransaction = "central_salma_transaction";
    public const string CentralSalmaVulnerability = "central_salma_vulnerability";
    public const string CentralSalmaConflict = "central_salma_conflict";
    public const string CentralSalmaOutcome = "central_salma_outcome";
    public const string CentralMahmoudTransaction = "central_mahmoud_transaction";
    public const string CentralMahmoudVulnerability = "central_mahmoud_vulnerability";
    public const string CentralMahmoudConflict = "central_mahmoud_conflict";
    public const string CentralMahmoudOutcome = "central_mahmoud_outcome";
    public const string CentralUmmKarimTransaction = "central_ummkarim_transaction";
    public const string CentralUmmKarimVulnerability = "central_ummkarim_vulnerability";
    public const string CentralUmmKarimConflict = "central_ummkarim_conflict";
    public const string CentralUmmKarimOutcome = "central_ummkarim_outcome";
}
